"""empty message

Revision ID: e64955c2f69e
Revises: 919d1503bdb4
Create Date: 2021-06-30 16:20:14.886093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64955c2f69e'
down_revision = '919d1503bdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('edited', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'edited')
    # ### end Alembic commands ###
